"""
Run the full multi-hop pipeline over all 5 questions and write a traceable
report to data/outputs/answers.md (and print to stdout).

Usage:  python -m rag.run_questions
"""

import os
from rag.pipeline import prepare, ALL, OUT_DIR


def render(idx, r):
    lines = [f"## Question {idx}", "", f"**{r['q']}**", "",
             "### Retrieval chain", ""]
    for h in r['hops']:
        lines.append(f"**Hop {h['n']} — {h['type']}**")
        lines.append(f"- *Query:* {h['query']}")
        lines.append(f"- *Retrieved:*")
        for item in h['retrieved']:
            lines.append(f"    - {item}")
        if h['note']:
            lines.append(f"- *Note:* {h['note']}")
        lines.append("")
    lines += ["### Synthesised answer", "", "```", r['answer'], "```", "",
              f"**Confidence: {r['confidence']}** — {r['confidence_reason']}",
              "", "---", ""]
    return "\n".join(lines)


def main():
    print("Preparing pipeline (structured pre-pass + player fetch + index)...")
    vs, title_of, pre = prepare()

    md = ["# Multi-Hop RAG — Answers to the 5 Questions", "",
          "Generated by `python -m rag.run_questions`. Each question chains "
          "at least 3 hops across Cricsheet (structured) and Wikipedia "
          "(semantic) sources.", "", "---", ""]

    for i, qfn in enumerate(ALL, 1):
        print(f"\n{'='*70}\nQUESTION {i}\n{'='*70}")
        r = qfn(vs, title_of, pre)
        block = render(i, r)
        print(block)
        md.append(block)

    out = os.path.join(OUT_DIR, 'answers.md')
    with open(out, 'w') as f:
        f.write("\n".join(md))
    print(f"\nWrote {out}")


if __name__ == '__main__':
    main()
